version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # NestJS Backend Service
  backend:
    build:
      context: ./backend
    container_name: nestjs-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: nestjs_db
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  # Svelte Frontend Service
  frontend:
    build:
      context: ./frontend
    container_name: svelte-frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

volumes:
  postgres_data: